### ISSUE TITLE
Task: tentative check endpoint

### ISSUE THREAD

**Issue by CakeCrusher** [OpenPluginACI/openplugin-api#1]
## Chat
https://chat.openai.com/share/8d5fffad-e3ca-492e-b62c-e5b42d7841a3
## Description
This endpoint will create the initial openpluginInfo for plugin testing. It will test for: manifest and its syntax, hard whitelisting (will whitelist its manifest)
## Tasks
These tasks are set up to be used as part of the ChatGPT prompts along with any additional context required. They don't need to be strictly followed but it is encouraged to use them as a guide.
- [x] Create a GET `/eval/tentative` endpoint that receives either a `plugin_name` or `root_url` and initializes a plugin with it and then populates a base `openplugin_info` object using the manifest, this endpoint will return a the `openplugin_info`. 
  - [x] When instantiating the plugin use `open_plugin_memo`, if it fails to initialize then that means that it is not whitelisted and thus should return an error.
  - [x] Get the manifest file and extract the relevant `openplugin_info` values, if any values are not present it should return an error.

**Comment by CakeCrusher** [comment]
#3
