### ISSUE TITLE
Task: support check endpoint

### ISSUE THREAD

**Issue by CakeCrusher** [OpenPluginACI/openplugin-api#2]
## Chat
https://chat.openai.com/share/8d5fffad-e3ca-492e-b62c-e5b42d7841a3
## Description
Create an endpoint that tests whether a plugin can earn a supported status. It will receive a domain and maybe a prompt. Then return either the API response or error.
## Tasks
These tasks are set up to be used as part of the ChatGPT prompts along with any additional context required. They don't need to be strictly followed but it is encouraged to use them as a guide.
- [x] Create GET /genereate_prompt which receives a `plugin_name` or `root_url`, initializes plugin and uses `.manifest.description_for_human` and `.manifest.description_for_model` generate a `stimulous_prompt` as it is done in `test_stimulate`
- [x] Create a GET `/eval/supported` endpoint that receives a `plugin_name` or `root_url` and a maybe a `prompt` and returns the plugin's API response or an error.
  - [x] It will initialize the plugin and if no prompt is provided then it will get one by pinging GET /genereate_prompt. Then it will transform the prompt into a message that it will send to POST /plugin . It will return the response from /plugin.

**Comment by CakeCrusher** [comment]
#4 completed
