### ISSUE TITLE
Task: Create oauth endpoints

### ISSUE THREAD

**Issue by CakeCrusher** [OpenPluginACI/openplugin-api#6]
## Chat
https://chat.openai.com/share/cd181779-6d66-4e6c-9a4c-4bfd25db80b0
## Description
To offer a oauth authentication in plugins this python API will need to offer two endpoints for handling the oauth exchange.
## Tasks
These tasks are set up to be used as part of the ChatGPT prompts along with any additional context required. They don't need to be strictly followed but it is encouraged to use them as a guide.
- [x] GET `/oauth_initialization` endpoint
  - [ ] it will receive as params `{client_id: string, client_domain: string, authorization_url: string, token_url: string, openplugin_callback_url: string, authorization_content_type: string}`
  - [ ] the session should store all of these variables so that once the user is done authenticating at the `authorization_url` this session can be retrieved
  - [ ] use `client.prepare_authorization_request` and redirect the user to the `authorization_url`
- [x] GET `/oauth_token` endpoint
  - [ ] it will receive param `state` and `code`  use these to get the current session
  - [ ] fetch the mongodb collection `openplugin-auth` by matching its `domain` with `client_domain` from the state and it will contain an object of type `OpenpluginAuth`, retrieve the client_secret from that.
  - [ ] make a post request to the `token_url` together with the `token` information received from `client.prepare_token_request`.  The `redirect_url` will be `/oauth_token`. make sure to use the correct headers and data depending on the `authorization_content_type`.
  - [ ] parse the response data with `client.parse_request_body_response` and redirect to `openplugin_callback_url` with the response (each of the items as URL parameters), the `client_domain`, and `oauth_token` as true passed as urlencoded params

**Comment by CakeCrusher** [comment]
completed df73a46
